PROVCAU-104 AJAX Summary Displays - Cleanup.
gaiaresources/providence pull request #30
Opened 2023-07-04 03:27 UTC by bri-gaia

2023-07-04 03:28 UTC, bri-gaia commented on app/lib/BaseEditorController.php
> +		if((defined('__CA_ENABLE_DEBUG_OUTPUT__') && __CA_ENABLE_DEBUG_OUTPUT__) || (bool)$this->request->config->get('display_template_debugger') || ($this->request->user->getPreference('show_template_deb
I think these make sense to place at the page load level, no need to replicate on every ajax request.

2023-07-04 03:29 UTC, bri-gaia commented on app/lib/BaseEditorController.php
> +	public function SummaryData($pa_options=null) {
Moved reused code into a separate function to make it easier to see which parts are specific to the 'section' we are collecting info for.

2023-07-04 03:30 UTC, bri-gaia commented on app/lib/BaseEditorController.php
>  		session_write_close();
do we need a session write close here and in summaryInfo() ?

2023-07-04 03:51 UTC, bri-gaia commented on app/lib/BaseEditorController.php
> +	public function SummaryInfo($pa_options=null, $pb_load_placement_info=TRUE) {
Use a named variable here to make it clear what it controls, move Ajax-y logic to where this function is called.

2023-07-04 03:57 UTC, bri-gaia commented on app/lib/BaseEditorController.php
> +		if ($pb_load_placement_info) {
If we invert the logic here and return on false, the code is a lot easier to compare to what is upstream (As it no longer needs to be indented, so git can match them up). 
Bit weird though.

2023-07-04 04:00 UTC, bri-gaia commented on app/lib/BaseEditorController.php
>  			if ($this->request->isAjax()) {
Is this the logical place to do this?

2023-07-05 03:58 UTC, bri-gaia commented on app/lib/BaseEditorController.php
> +		if((defined('__CA_ENABLE_DEBUG_OUTPUT__') && __CA_ENABLE_DEBUG_OUTPUT__) || (bool)$this->request->config->get('display_template_debugger') || ($this->request->user->getPreference('show_template_deb
Add Access check before rendering this.

2023-07-05 08:53 UTC, kehh commented
ah booo conflix

2023-07-06 01:46 UTC, kehh requested changes
Tiny tweaks but looking great.

2023-07-06 01:46 UTC, kehh commented on app/lib/BaseEditorController.php
>  		session_write_close();
happy for this to go

2023-07-06 01:46 UTC, kehh commented on app/lib/BaseEditorController.php
> +		$ajax_placement_id = $_GET['va_placement_id'];
can this be replaced with $this->getRequest()->getParam('va_placement_id') and then use the variable in the setVar below? I know it's from the pre-existing code but use of $_GET should be avoided.

2023-07-06 01:46 UTC, kehh commented on app/lib/BaseEditorController.php
> +		$ajax_placement_id = $_GET['va_placement_id'];
also to follow the CA coding style it should be vn_placement_id or simply placement_id (newer code removes the crazy data typing prefix)

2023-07-06 01:59 UTC, merged